// noinspection NestedAssignmentJS,AssignmentResultUsedJS

"use strict";
import {hardware_cast, hardware_cast_connected, hardware_computer, hardware_desktop_mac, hardware_desktop_windows, hardware_developer_board, hardware_device_hub, hardware_devices_other, hardware_dock, hardware_gamepad, hardware_headset, hardware_headset_mic, hardware_keyboard, hardware_keyboard_arrow_down, hardware_keyboard_arrow_left, hardware_keyboard_arrow_right, hardware_keyboard_arrow_up, hardware_keyboard_backspace, hardware_keyboard_capslock, hardware_keyboard_hide, hardware_keyboard_return, hardware_keyboard_tab, hardware_keyboard_voice, hardware_laptop, hardware_laptop_chromebook, hardware_laptop_mac, hardware_laptop_windows, hardware_memory, hardware_mouse, hardware_phone_android, hardware_phone_iphone, hardware_phonelink, hardware_phonelink_off, hardware_power_input, hardware_router, hardware_scanner, hardware_security, hardware_sim_card, hardware_smartphone, hardware_speaker, hardware_speaker_group, hardware_tablet, hardware_tablet_android, hardware_tablet_mac, hardware_toys, hardware_tv, hardware_videogame_asset, hardware_watch} from '../icons.js';

if(window.icons === undefined){ window.icons = {}; }
window.icons["hardware:cast"] = window.icons["cast"] = hardware_cast;
window.icons["hardware:cast-connected"] = window.icons["cast-connected"] = hardware_cast_connected;
window.icons["hardware:computer"] = window.icons["computer"] = hardware_computer;
window.icons["hardware:desktop-mac"] = window.icons["desktop-mac"] = hardware_desktop_mac;
window.icons["hardware:desktop-windows"] = window.icons["desktop-windows"] = hardware_desktop_windows;
window.icons["hardware:developer-board"] = window.icons["developer-board"] = hardware_developer_board;
window.icons["hardware:device-hub"] = window.icons["device-hub"] = hardware_device_hub;
window.icons["hardware:devices-other"] = window.icons["devices-other"] = hardware_devices_other;
window.icons["hardware:dock"] = window.icons["dock"] = hardware_dock;
window.icons["hardware:gamepad"] = window.icons["gamepad"] = hardware_gamepad;
window.icons["hardware:headset"] = window.icons["headset"] = hardware_headset;
window.icons["hardware:headset-mic"] = window.icons["headset-mic"] = hardware_headset_mic;
window.icons["hardware:keyboard"] = window.icons["keyboard"] = hardware_keyboard;
window.icons["hardware:keyboard-arrow-down"] = window.icons["keyboard-arrow-down"] = hardware_keyboard_arrow_down;
window.icons["hardware:keyboard-arrow-left"] = window.icons["keyboard-arrow-left"] = hardware_keyboard_arrow_left;
window.icons["hardware:keyboard-arrow-right"] = window.icons["keyboard-arrow-right"] = hardware_keyboard_arrow_right;
window.icons["hardware:keyboard-arrow-up"] = window.icons["keyboard-arrow-up"] = hardware_keyboard_arrow_up;
window.icons["hardware:keyboard-backspace"] = window.icons["keyboard-backspace"] = hardware_keyboard_backspace;
window.icons["hardware:keyboard-capslock"] = window.icons["keyboard-capslock"] = hardware_keyboard_capslock;
window.icons["hardware:keyboard-hide"] = window.icons["keyboard-hide"] = hardware_keyboard_hide;
window.icons["hardware:keyboard-return"] = window.icons["keyboard-return"] = hardware_keyboard_return;
window.icons["hardware:keyboard-tab"] = window.icons["keyboard-tab"] = hardware_keyboard_tab;
window.icons["hardware:keyboard-voice"] = window.icons["keyboard-voice"] = hardware_keyboard_voice;
window.icons["hardware:laptop"] = window.icons["laptop"] = hardware_laptop;
window.icons["hardware:laptop-chromebook"] = window.icons["laptop-chromebook"] = hardware_laptop_chromebook;
window.icons["hardware:laptop-mac"] = window.icons["laptop-mac"] = hardware_laptop_mac;
window.icons["hardware:laptop-windows"] = window.icons["laptop-windows"] = hardware_laptop_windows;
window.icons["hardware:memory"] = window.icons["memory"] = hardware_memory;
window.icons["hardware:mouse"] = window.icons["mouse"] = hardware_mouse;
window.icons["hardware:phone-android"] = window.icons["phone-android"] = hardware_phone_android;
window.icons["hardware:phone-iphone"] = window.icons["phone-iphone"] = hardware_phone_iphone;
window.icons["hardware:phonelink"] = window.icons["phonelink"] = hardware_phonelink;
window.icons["hardware:phonelink-off"] = window.icons["phonelink-off"] = hardware_phonelink_off;
window.icons["hardware:power-input"] = window.icons["power-input"] = hardware_power_input;
window.icons["hardware:router"] = window.icons["router"] = hardware_router;
window.icons["hardware:scanner"] = window.icons["scanner"] = hardware_scanner;
window.icons["hardware:security"] = window.icons["security"] = hardware_security;
window.icons["hardware:sim-card"] = window.icons["sim-card"] = hardware_sim_card;
window.icons["hardware:smartphone"] = window.icons["smartphone"] = hardware_smartphone;
window.icons["hardware:speaker"] = window.icons["speaker"] = hardware_speaker;
window.icons["hardware:speaker-group"] = window.icons["speaker-group"] = hardware_speaker_group;
window.icons["hardware:tablet"] = window.icons["tablet"] = hardware_tablet;
window.icons["hardware:tablet-android"] = window.icons["tablet-android"] = hardware_tablet_android;
window.icons["hardware:tablet-mac"] = window.icons["tablet-mac"] = hardware_tablet_mac;
window.icons["hardware:toys"] = window.icons["toys"] = hardware_toys;
window.icons["hardware:tv"] = window.icons["tv"] = hardware_tv;
window.icons["hardware:videogame-asset"] = window.icons["videogame-asset"] = hardware_videogame_asset;
window.icons["hardware:watch"] = window.icons["watch"] = hardware_watch;
