// noinspection NestedAssignmentJS,AssignmentResultUsedJS

"use strict";
import {notification_adb, notification_airline_seat_flat, notification_airline_seat_flat_angled, notification_airline_seat_individual_suite, notification_airline_seat_legroom_extra, notification_airline_seat_legroom_normal, notification_airline_seat_legroom_reduced, notification_airline_seat_recline_extra, notification_airline_seat_recline_normal, notification_bluetooth_audio, notification_confirmation_number, notification_disc_full, notification_do_not_disturb, notification_do_not_disturb_alt, notification_do_not_disturb_off, notification_do_not_disturb_on, notification_drive_eta, notification_enhanced_encryption, notification_event_available, notification_event_busy, notification_event_note, notification_folder_special, notification_live_tv, notification_mms, notification_more, notification_network_check, notification_network_locked, notification_no_encryption, notification_ondemand_video, notification_personal_video, notification_phone_bluetooth_speaker, notification_phone_forwarded, notification_phone_in_talk, notification_phone_locked, notification_phone_missed, notification_phone_paused, notification_power, notification_priority_high, notification_rv_hookup, notification_sd_card, notification_sim_card_alert, notification_sms, notification_sms_failed, notification_sync, notification_sync_disabled, notification_sync_problem, notification_system_update, notification_tap_and_play, notification_time_to_leave, notification_vibration, notification_voice_chat, notification_vpn_lock, notification_wc, notification_wifi} from '../icons.js';

if(window.icons === undefined){ window.icons = {}; }
window.icons["notification:adb"] = window.icons["adb"] = notification_adb;
window.icons["notification:airline-seat-flat"] = window.icons["airline-seat-flat"] = notification_airline_seat_flat;
window.icons["notification:airline-seat-flat-angled"] = window.icons["airline-seat-flat-angled"] = notification_airline_seat_flat_angled;
window.icons["notification:airline-seat-individual-suite"] = window.icons["airline-seat-individual-suite"] = notification_airline_seat_individual_suite;
window.icons["notification:airline-seat-legroom-extra"] = window.icons["airline-seat-legroom-extra"] = notification_airline_seat_legroom_extra;
window.icons["notification:airline-seat-legroom-normal"] = window.icons["airline-seat-legroom-normal"] = notification_airline_seat_legroom_normal;
window.icons["notification:airline-seat-legroom-reduced"] = window.icons["airline-seat-legroom-reduced"] = notification_airline_seat_legroom_reduced;
window.icons["notification:airline-seat-recline-extra"] = window.icons["airline-seat-recline-extra"] = notification_airline_seat_recline_extra;
window.icons["notification:airline-seat-recline-normal"] = window.icons["airline-seat-recline-normal"] = notification_airline_seat_recline_normal;
window.icons["notification:bluetooth-audio"] = window.icons["bluetooth-audio"] = notification_bluetooth_audio;
window.icons["notification:confirmation-number"] = window.icons["confirmation-number"] = notification_confirmation_number;
window.icons["notification:disc-full"] = window.icons["disc-full"] = notification_disc_full;
window.icons["notification:do-not-disturb"] = window.icons["do-not-disturb"] = notification_do_not_disturb;
window.icons["notification:do-not-disturb-alt"] = window.icons["do-not-disturb-alt"] = notification_do_not_disturb_alt;
window.icons["notification:do-not-disturb-off"] = window.icons["do-not-disturb-off"] = notification_do_not_disturb_off;
window.icons["notification:do-not-disturb-on"] = window.icons["do-not-disturb-on"] = notification_do_not_disturb_on;
window.icons["notification:drive-eta"] = window.icons["drive-eta"] = notification_drive_eta;
window.icons["notification:enhanced-encryption"] = window.icons["enhanced-encryption"] = notification_enhanced_encryption;
window.icons["notification:event-available"] = window.icons["event-available"] = notification_event_available;
window.icons["notification:event-busy"] = window.icons["event-busy"] = notification_event_busy;
window.icons["notification:event-note"] = window.icons["event-note"] = notification_event_note;
window.icons["notification:folder-special"] = window.icons["folder-special"] = notification_folder_special;
window.icons["notification:live-tv"] = window.icons["live-tv"] = notification_live_tv;
window.icons["notification:mms"] = window.icons["mms"] = notification_mms;
window.icons["notification:more"] = window.icons["more"] = notification_more;
window.icons["notification:network-check"] = window.icons["network-check"] = notification_network_check;
window.icons["notification:network-locked"] = window.icons["network-locked"] = notification_network_locked;
window.icons["notification:no-encryption"] = window.icons["no-encryption"] = notification_no_encryption;
window.icons["notification:ondemand-video"] = window.icons["ondemand-video"] = notification_ondemand_video;
window.icons["notification:personal-video"] = window.icons["personal-video"] = notification_personal_video;
window.icons["notification:phone-bluetooth-speaker"] = window.icons["phone-bluetooth-speaker"] = notification_phone_bluetooth_speaker;
window.icons["notification:phone-forwarded"] = window.icons["phone-forwarded"] = notification_phone_forwarded;
window.icons["notification:phone-in-talk"] = window.icons["phone-in-talk"] = notification_phone_in_talk;
window.icons["notification:phone-locked"] = window.icons["phone-locked"] = notification_phone_locked;
window.icons["notification:phone-missed"] = window.icons["phone-missed"] = notification_phone_missed;
window.icons["notification:phone-paused"] = window.icons["phone-paused"] = notification_phone_paused;
window.icons["notification:power"] = window.icons["power"] = notification_power;
window.icons["notification:priority-high"] = window.icons["priority-high"] = notification_priority_high;
window.icons["notification:rv-hookup"] = window.icons["rv-hookup"] = notification_rv_hookup;
window.icons["notification:sd-card"] = window.icons["sd-card"] = notification_sd_card;
window.icons["notification:sim-card-alert"] = window.icons["sim-card-alert"] = notification_sim_card_alert;
window.icons["notification:sms"] = window.icons["sms"] = notification_sms;
window.icons["notification:sms-failed"] = window.icons["sms-failed"] = notification_sms_failed;
window.icons["notification:sync"] = window.icons["sync"] = notification_sync;
window.icons["notification:sync-disabled"] = window.icons["sync-disabled"] = notification_sync_disabled;
window.icons["notification:sync-problem"] = window.icons["sync-problem"] = notification_sync_problem;
window.icons["notification:system-update"] = window.icons["system-update"] = notification_system_update;
window.icons["notification:tap-and-play"] = window.icons["tap-and-play"] = notification_tap_and_play;
window.icons["notification:time-to-leave"] = window.icons["time-to-leave"] = notification_time_to_leave;
window.icons["notification:vibration"] = window.icons["vibration"] = notification_vibration;
window.icons["notification:voice-chat"] = window.icons["voice-chat"] = notification_voice_chat;
window.icons["notification:vpn-lock"] = window.icons["vpn-lock"] = notification_vpn_lock;
window.icons["notification:wc"] = window.icons["wc"] = notification_wc;
window.icons["notification:wifi"] = window.icons["wifi"] = notification_wifi;
